### PR TITLE
Add volume property to Navigation branch

### PR DESCRIPTION
**Pull request by wonsuk73**
It need to have a volume property of Navigation to control the navigation guidance volume.

### CODE REVIEW

**Review by erikbosch — APPROVED** [review]
Looks good to me, same range set as Media.Volume.
New PR so shall preferably be merged at earliest next week to give time for additional comments

**Comment by erikbosch** [comment]
Meeting notes:

Add "unit: percent" on both the new signal and the old signal Media.Volume. Ready to be merged when updated.

**Comment by wonsuk73** [comment]
@erikbosch Thanks for additional comment! I have done the update with meeting result!

**Review by adobekan — APPROVED** [review]
Looks good.

**Pull request merged**
