### PR TITLE
Support negative torque for combustion engine

### PR DESCRIPTION
**Pull request by ppb2020**
Some combustion engine vehicles report a negative torque under braking conditions. This cannot be properly reflected by the current definition of engine torque as it is an unsigned integer.

This change proposes modifying the combustion engine torque definition from an unsigned integre to an integer.

Signed-off-by: Pierre Pierre Blais <ppblais@BlackBerry.com>

### CODE REVIEW

**Comment by ppb2020** [comment]
I presume that I can add a commit with just a comment, so that the sign off is in a commit.

**Comment by erikbosch** [comment]
Meeting notes:

- Please review
- Merge candidate for next meeting

**Comment by erikbosch** [comment]
Meeting notes:

- Pierre to check if he "fix" the PR so CI pass
- Ok to merge when fixed

**Comment by erikbosch** [comment]
@ppb2020 - have you check if you can update the PR/commit, or should I assist with a "workaround"?

**Comment by ppb2020** [comment]
I have not been able to resolve the squashing issue as I always end up with two commits. Closing the PR. Will resubmit the change.

**Pull request closed without merging**
