### PR TITLE
Fix a typo in the license documentation

### PR DESCRIPTION
**Pull request by violinyanev**
Fixed a simple typo in the license documentation.

### CODE REVIEW

**Comment by erikbosch** [comment]
Thank you for your PR. The DCO check in continuous integration fails. This is because your commit does not have a signoff, see https://covesa.global/contribute. Please amend a signoff to the commit and do a force push (e.g. `git commit --amend -s; git push -f ...`)

**Review by ppb2020 — COMMENTED** [review]
Looks good. To be approved once commit is fixed.

**Comment by violinyanev** [comment]
image
 ;) Sorry, did the commit with the web UI and for some reason it didn't apply my signature..

**Comment by erikbosch** [comment]
Looks good now. As this is a trivial fix I will merge it right now. (Larger pull requests are typically kept open for a longer time period to allow for more reviews)

**Review by erikbosch — APPROVED** [review]

**Pull request merged**
