### PR TITLE
Adding more unit information

### PR DESCRIPTION
**Pull request by erikbosch**
this commit introduces VSS signals for the following Android VHAL properties

VEHICLE_SPEED_DISPLAY_UNITS
EV_BATTERY_DISPLAY_UNITS

See https://android.googlesource.com/platform/hardware/interfaces/+/master/automotive/vehicle/2.0/types.hal

### CODE REVIEW

**Comment by erikbosch** [comment]
Please review

**Comment by nickrbb** [comment]
Just for consistency, the HMI.SpeedUnit of 'METER_PER_SECOND' should be plural i.e. 'METERS_PER_SECOND'.

**Review by adobekan — APPROVED** [review]
Looks good

**Comment by erikbosch** [comment]
Updated, so then I assume it is ready to merge

**Comment by nickrbb** [comment]
I see my comment is resolved, so I have no objections to merge.

**Pull request merged**
