### PR TITLE
Doc Update

### LINKED ISSUE #791: Errors in https://covesa.github.io/vehicle_signal_specification/catalog/index.html
https://covesa.github.io/vehicle_signal_specification/catalog/index.html is rendered with mistakes.
Screenshot 2024-11-18 at 10 33 16

### PR DESCRIPTION
**Pull request by erikbosch**
Fixes #791

### CODE REVIEW

**Review by SebastianSchildt — CHANGES_REQUESTED** [review]
This fixes the double header, but it still says "chapter 25" on top for me

image

**Comment by SebastianSchildt** [comment]
`chapter: false`fixed it, but are all the Makefile changes intended?

**Comment by erikbosch** [comment]
> `chapter: false`fixed it, but are all the Makefile changes intended?

Nope, should be removed now

**Review by SebastianSchildt — APPROVED** [review]
Now I like it!

**Pull request merged**
