### PR TITLE
Refactor Makefile for binary

### PR DESCRIPTION
**Pull request by erikbosch**
This is the last part of
https://github.com/COVESA/vss-tools/issues/121

### CODE REVIEW

**Comment by erikbosch** [comment]
MoM: Please review, especially @UlfBj

**Comment by UlfBj** [comment]
If the gcc command is remove from here it needs to be called elsewhere, e. g. in the vspec2binary.py.

**Comment by erikbosch** [comment]
> If the gcc command is remove from here it needs to be called elsewhere, e. g. in the vspec2binary.py.

Yes, and that is what happens, as we call `cd ${TOOLSDIR}/binary && $(MAKE)`. That means we enter `vss-tools/binary` directory and execute `make` there, which triggers `gcc`. See example below. So actual behavior shall be the same.

```
erik@debian4:~/vehicle_signal_specification$ make binary
cd ./vss-tools/binary && make
make[1]: Entering directory '/home/erik/vss-tools/binary'
rm -f binarytool.so
gcc -shared -o binarytool.so -fPIC binarytool.c
make[1]: Leaving directory '/home/erik/vss-tools/binary'
./vss-tools/vspec2binary.py --uuid -u ./spec/units.yaml ./spec/VehicleSignalSpecification.vspec vss_rel_$(cat VERSION).binary
INFO     Known extended attributes: 
INFO     Added 29 quantities from /home/erik/vehicle_signal_specification/spec/quantities.yaml
INFO     Added 61 units from ./spec/units.yaml
INFO     Loading vspec from ./spec/VehicleSignalSpecification.vspec...
INFO     Calling exporter...
INFO     Generating binary output...
INFO     Binary output generated in vss_rel_5.0-dev.binary
INFO     All done.
```

**Comment by UlfBj** [comment]
@erikbosch, thanks for the explanation. After understanding it I see no problem with this.

**Pull request merged**
